apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: o11y-grafana
  namespace: monitoring
spec:
  serviceRef:
    name: o11y-grafana
    port: 80
  targetGroupARN: __GRAFANA_TG_ARN__
  targetType: ip
  networking:
    ingress:
      - from:
          - securityGroup:
              groupID: __ALB_SG_ID__
        ports:
          - protocol: TCP
            port: 3000
